CC = g++

all:
	$(CC) -mfma -fopenmp -O3 main.cpp ../../src/Ham_U.cpp ../../src/W.cpp ../../src/ProjectionMatrices.cpp ../../src/Quantum_chaotic_billiard.cpp ../../src/Save_txt_files.cpp -o Unitary
clean:
	rm Unitary
