CC = g++

all:
	$(CC) -mfma -fopenmp -O3 main.cpp ../../src/Ham_O.cpp ../../src/W.cpp ../../src/ProjectionMatrices.cpp ../../src/Quantum_chaotic_billiard.cpp ../../src/Save_txt_files.cpp -o Orthogonal
clean:
	rm Orthogonal
