CC = g++

all:
	$(CC) -mfma -fopenmp -O3 Orthogonal.cpp ../../src/Ham_O.cpp ../../src/W_O.cpp ../../src/ProjectionMatrices_O.cpp ../../src/Quantum_chaotic_billiard_O.cpp -o Orthogonal
clean:
	rm Orthogonal
